# NumPy

In [1]:
import numpy as np

In [12]:
np.pi # pi number

3.141592653589793

In [2]:
a=np.array([0,1,2,3,4])

In [5]:
print(a.size)   # attribute, number of elements
print(a.ndim)   # dimension, =1
print(a.shape)  # size and dimensions

5
1
(5,)


In [6]:
b=np.array([0,1.5,2.2,3.145,4])
b.dtype   # float64

dtype('float64')

In [8]:
#indexing and slicing

d = a[1:4]
d

array([1, 2, 3])

In [9]:
# Vectors additions and multiplications:

u=[1,0]
v=[0,1]
z=[]
for n,m in zip(u,v):    # this is in pure Python
    z.append(n+m)
print(z)

[1, 1]


In [10]:
# in np it is much simpler:

u=np.array([1,0])
v=np.array([0,1])
y=u-v

y*2

array([ 2, -2])

In [11]:
u+5  # broadcasting; adds 5 to each element
z = u * v
z

array([0, 0])

In [ ]:
np.dot(u,v)  # Dot product of two arrays. 

# Universal funtions:

.mean()
.max()

In [ ]:
np.linspace(-2,2,num=5)  # generates a vector with 5 elements, from -2 to 2

x = np.linespace(0, 2*np.pi, 100)
y=nb.sin(x)  # applies sin to each element of the vector


a=np.array([0,1,0,1,0])
b=np.array([1,0,1,0,1])
a*b

In [ ]:
# Two dimensional Numpy (i.e. matrix)

a = [[11,12,13], [21,22,23],[31,32,33]]

A=np.array(a)

A.ndim
A.shape  # rows, columns
A.size
A[n][m]  value 

#slicing:
A[0,0:2] # first row, first two columns

In [ ]:
# Matrix operations:

X,Y # 2x2 matrix

Z=X+Y

Z*2  # multiplies each element by 2

X*Y # multiplies each correstponding element